HS #7 función de contar estrellas de repos github (no fork)
UTN-MDP/2017 pull request #23
Opened 2017-08-31 23:12 UTC by matirey

La función cuenta la cantidad total de valuaciones que tiene el usuario en cada repositorio excluyendo los que sean Fork de otros repositorios.

2017-09-01 14:46 UTC, zeratulmdq commented
Lo que hiciste funciona joya. Por ser la primera vez, si no querés cambiar nada no lo hagas, pero tenés posibilidad de mejorar tres cosas para una mejor nota:

1) Nombres. Las variables/parámetros deberían llevar nombres que, aun sin saber que hace la función, te den una idea. Por ejemplo, si te fijas la firma de tu función **estrellas_no_fork** no te dice nada. Justo este caso no te permite poner un nombre descriptivo corto, pero debería ser algo como **countNoForkReposStars**. Además, el parámetro que pasas debería ser algo como **userRepoList** y no **jsonresponse**, para que quien use tu función sepa que tiene que pasarle (sobretodo porque no agregaste un DocBlock arriba, no se pidió, no te preocupes). __Result__ e __i__ también mismo problema.
2) El usuario no necesita feedback en la consola de lo que pasa, eso dejalo para vos si querés mientras debuggueas pero al momento de subir el código a "producción", borralo.
3) El for funciona perfecto, pero como decía el canal de slack, la idea es usar Array extras. Una mejor nota seria con forEach(). Una nota perfecta con reduce(), que te permite hacer toda la función en una sola línea.

Modifiques o no lo que te pido, dejame un comentario para saber si mergeo o no. Si para el lunes no respondes significa que estás contento con este resultado.

2017-09-02 21:24 UTC, matirey commented
ahi te añadi los cambios, puse lo que me pediste aunque no encontre forma de hacerlo unicamente con 1 reduce, quizas la haya pero no lo comprendo del todo bien como funciona, asi que use un forEach(), separe en un array externo la cantidad de estrellas y use el reduce() solo para obtener el total de un array solo de numeros

2017-09-02 22:38 UTC, zeratulmdq requested changes
El comentario anterior era usar el **forEach** o el **reduce**, no los dos. Si ponés return adelante de arrStars.reduce podés borrar __todo lo demás__, no necesitás ni siquiera declarar una variable. Usa el mismo condicional que usaste en el forEach dentro del reduce y retorna cero si no se cumple la condición.

2017-09-03 00:34 UTC, matirey reviewed
no pude hacer andar el reduce ni como me dijiste ni de otra manera, asi que solo lo deje con forEach() y lo mas simplificado posible

2017-09-03 00:35 UTC, zeratulmdq approved these changes

2017-09-03 00:35 UTC, merged