Task Done
UTN-MDP/2017 pull request #24
Opened 2017-09-01 14:28 UTC by Facundo97Maldonado

2017-09-01 15:14 UTC, zeratulmdq commented
Está perfecta la tarea, algunas cosas que deberías cambiar para mejorar la nota.

1) Hay que subir un solo archivo. Como tenés que agregar dependencias externas, deberías usar CDN para todo (como hiciste con jQuery). No es obligación en todos los proyectos que sea así, pero es un lineamiento para este en particular. Para el tema de las imágenes, te recomiendo https://unsplash.it/ que te permite elegir imágenes y tamaño para mostrar en una página.

2) __Tamano__ no existe en español. Usa un tag meta con charset UTF8 o agrega el código HTML para que salga una eñe.

3) Los tag meta ponelos justo abajo de HEAD. El meta charset primero de todos.

4) Como observación extra, si por alguna razón necesitas subir archivos, solo tenés que agregar los que utilizas, no todos los que vienen con el paquete (por ejemplo, .min.css y .css, en la página solo hacés referencia a uno).

2017-09-01 15:25 UTC, Facundo97Maldonado commented
Eso te iba a preguntar. Pasa que si no tenes internet no se supone que no
funciona? Por eso lo tenia local. El jquery lo deje asi por no buscarlo
nomas. Puse tamaño por no tenerlo en la compu jajaja. Ahora lo cambio. Y
dale el resto tambien asi subo ls nota. En un ratito vuelvo a pushear.
Gracias por las observaciones!

El 1 sept. 2017 12:14, "zeratulmdq" <notifications@github.com> escribió:

> Está perfecta la tarea, algunas cosas que deberías cambiar para mejorar la
> nota.
>
>    1.
>
>    Hay que subir un solo archivo. Como tenés que agregar dependencias
>    externas, deberías usar CDN para todo (como hiciste con jQuery). No es
>    obligación en todos los proyectos que sea así, pero es un lineamiento para
>    este en particular. Para el tema de las imágenes, te recomiendo
>    https://unsplash.it/ que te permite elegir imágenes y tamaño para
>    mostrar en una página.
>    2.
>
>    *Tamano* no existe en español. Usa un tag meta con charset UTF8 o
>    agrega el código HTML para que salga una eñe.
>    3.
>
>    Los tag meta ponelos justo abajo de HEAD. El meta charset primero de
>    todos.
>    4.
>
>    Como observación extra, si por alguna razón necesitas subir archivos,
>    solo tenés que agregar los que utilizas, no todos los que vienen con el
>    paquete (por ejemplo, .min.css y .css, en la página solo hacés referencia a
>    uno).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UTN-MDP/2017/pull/24#issuecomment-326607258>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AabCdw2gbJG4pOF1-oB8YAETdOBKzLjTks5seB9jgaJpZM4PKObw>
> .
>

2017-09-01 20:37 UTC, zeratulmdq requested changes
Fijate que subiste los cambios pero no borraste los archivos anteriores. Los commits son sucesivos, en este momento si mergeo todo lo que me pusiste subo todo lo anterior. El resto de las cosas está bien salvo las imágenes. En parallax estás usando un img que apunta a la imagen que subiste y tenés que usar un solo archivo, no podés subir imágenes. Usa el link que te pasé.

2017-09-01 20:39 UTC, Facundo97Maldonado commented
Ah no entendi lo de que imagenes tampoco. Hago quw apunte a la pagina,
genial.
De lo otro, si siguen en rojo deberia sacarlos igual entonces?

El 1 sept. 2017 17:37, "zeratulmdq" <notifications@github.com> escribió:

> *@zeratulmdq* requested changes on this pull request.
>
> Fijate que subiste los cambios pero no borraste los archivos anteriores.
> Los commits son sucesivos, en este momento si mergeo todo lo que me pusiste
> subo todo lo anterior. El resto de las cosas está bien salvo las imágenes.
> En parallax estás usando un img que apunta a la imagen que subiste y tenés
> que usar un solo archivo, no podés subir imágenes. Usa el link que te pasé.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/UTN-MDP/2017/pull/24#pullrequestreview-60236901>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AabCd6RlsT6kyIME3HXQZHRo49QBoCkpks5seGr4gaJpZM4PKObw>
> .
>

2017-09-01 20:59 UTC, zeratulmdq commented
Deberías borrar todos los archivos de tu disco rígido (hay otras maneras, pero es la mas fácil esa) y si haces un git status vas a ver que git te muestra que se borraron. git add, git commit... y todo el resto del flujo. Tu repo en la rama tp2 debería tener solo el archivo maldonado.html y eso mismo se ve reflejado aca

2017-09-02 12:04 UTC, zeratulmdq approved these changes

2017-09-02 12:04 UTC, merged