tarea #15 listar usuarios con numeros de gists
UTN-MDP/2017 pull request #29
Opened 2017-09-02 16:52 UTC by DanielScha

La tarea pide crear una funcion, que recibe por parametro la lista de gists, y retorna un arreglo de objetos con los usuarios, y la cantidad de gists que hizo cada uno.

2017-09-02 18:01 UTC, zeratulmdq requested changes
Así como lo subiste no funciona. Tené en cuenta:

1) No tenés acceso a gists donde querés acceder vos. Directamente poné esa función como anónima en el find (copia y pega la definición y listo).

2) gist.owner no existe, fijate el objeto que estás usando.

3) Cuando creas el objeto en el else, estás poniendo los gists en cero. Si es el primer gist que tiene debería ser uno (o tenés que sumar después de inicializar).

4) Me olvidaba. Revisa que __jsonListOfAllgists__ está escrito diferente en diferentes lugares.

2017-09-03 02:36 UTC, DanielScha commented
No entendí bien la segunda anotación, no puse gist.owner en ningún lado, puse gist.user.... seguro te referías a eso igual,  entonces lo que debería usar creo que sería gist.owner.login? Es el nombre la única información del usuario que tiene que estar en el objeto que retorno? (además de la cantidad de gist, por supuesto).

2017-09-03 12:14 UTC, zeratulmdq commented
Fijate la propiedad user del objeto que pusiste de ejemplo, es null. El usuario que es dueño del gist se accede a través de gist.owner.login

2017-09-04 12:21 UTC, zeratulmdq approved these changes

2017-09-04 12:21 UTC, merged