Tp2
UTN-MDP/2017 pull request #31
Opened 2017-09-02 19:23 UTC by maurogsp

Cree una funcion que reciba como parametro su limite actual de consultas tal cual lo retorna la API y devuelva el intervalo en segundos que deberia pasar entre sus proximas consultas para no quedar banneado.

2017-09-02 21:56 UTC, zeratulmdq requested changes
El ejercicio está perfecto pero fijate que por alguna razón modificaste el archivo README.md también. Resetea los cambios en ese archivo y volve a pushear y estás listo. Si entrás acá o a tu repo deberías ver que en **Files changed** aparezca el número 1 en vez de 2 como ahora.

2017-09-02 22:04 UTC, maurogsp commented
Me había dado cuenta pero no se que modifique porque no lo toque a ese archivo, me fijo como esta en el repo original, lo dejo igual y vuelvo a pushear

2017-09-02 22:32 UTC, maurogsp commented
Pregunta: si pusheo de vuelta a MI repo remoto, tengo que hacer de vuelta el pull request?

2017-09-02 22:38 UTC, zeratulmdq commented
Es automático, cualquier cosa que pushees a tu repo aparece automágicamente acá.

2017-09-02 22:41 UTC, maurogsp commented
Joiaaa gracias tinchoo

2017-09-03 00:54 UTC, zeratulmdq approved these changes

2017-09-03 00:54 UTC, merged

2017-09-03 00:54 UTC, zeratulmdq commented
Quedo mal igual el archivo README pero lo dejamos así por ser la primera vez. Después en clase explico bien como resetear a cero todo.