no esta funcionando 100%, solo quiero sacarme esto de encima
UTN-MDP/2017 pull request #33
Opened 2017-09-02 20:11 UTC by co0per

en la funcion "ordenar_lista" cuando quiero seleccionar una propiedad de currentValue (ej: currentValue.id) me tira undefined y no deberia, cuando ya hice lo mismo en otra funcion y funciono

2017-09-02 22:28 UTC, zeratulmdq requested changes
Te enroscaste bastante pero anda, tenés que cambiar unas pavadas nada más. 

1) Fijate que tu funcion **quitar_obtener_mayor** no devuelve un usuario, devuelve un arreglo de un solo usuario, por eso te está dando undefined.

2) Aunque funciona, estás llamando a **boton** y a **lista_desordenada** directamente. Usa getElementById para referenciar elementos del DOM para no tener problemas de compatibilidad.

3) Crea la tarea de implementación y ponela en READY FOR TEST cuando esté listo para que lo verifique yo!

2017-09-05 17:44 UTC, zeratulmdq reviewed
Ahora si, los cambios funcionan. Para que quede perfecto, si podés antes de la clase de hoy, fijate que editaste el archivo README.md también, que no deberías haber modificado. Además, limpia los console.log que te quedaron. Hay un par de cositas más pero no son importantes (lo anterior tampoco, salvo lo del README), lo vemos en clase.

2017-09-06 22:25 UTC, co0per commented
ahi creo que lo solucione, es lo que buscabas?

2017-09-07 19:48 UTC, zeratulmdq approved these changes

2017-09-07 19:48 UTC, zeratulmdq commented
Arreglaste lo del README pero no lo otro. Igual no importa, lo mergeo y que quede, las diferencias las arreglo yo ahora.

2017-09-07 19:49 UTC, merged